---
- hosts: us-west-2
  become: yes
  become_method: sudo
  tasks:
    - name: Update things on instance of ec2
      apt: update_cache=yes
      become_method: sudo
    - name: Install nginx, git, python3, python3-pip, python3.4-venv
      apt: name={{ item }} state=latest
      with_items:
        - nginx
        - git
        - python3
        - python3-pip
        - python3.4-venv
        - python-dev
    - name: Clone things from git
      git:
        clone=yes
        repo=https://github.com/poundsxd/django-imager.git
        dest=/home/ubuntu/django_imager/
    - name: Create venv
      command: python3 -m venv /home/ubuntu/django_imager/ENV
    - name: Install gunicorn to VENV
      pip:
        virtualenv=/home/ubuntu/django_imager/ENV
        name={{ item }}
      with_items:
        - gunicorn
    - name: Register old default
      stat: path=/etc/nginx/sites-available/default.old
      register: default_stat
    - name: Rename old default file
      command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.pip
      when: not default_stat.stat.exists
    - name: Create new default file for nginx
      template:
        src=/home/nosrac/codefellows/401/Ansible/templates/simple_nginx_config
        dest=/etc/nginx/sites-available/default
    - name: Restart the nginx service
      service:
        name=nginx
        state=restarted
      become: yes
      become_method: sudo
    - name: Copy upstart script into etc
      template:
        src=/home/nosrac/codefellows/401/Ansible/templates/gunicorn.conf
        dest=/etc/init/
    - pip:
        virtualenv: /home/ubuntu/django_imager/ENV
        requirements: /home/ubuntu/django_imager/requirements.pip
    - name: Start the ImagerSite app
      service:
        name=gunicorn
        state=restarted
      become: yes
      become_method: sudo
